### ISSUE TITLE
Kale Thyself 🤔#0676 @harvestcraft:kale 🥬 (35 points)

### ISSUE THREAD

**Issue by Foreck1** [Rebirth-of-the-Night/RotN-Bounty-Board#14]
Install this mod https://www.curseforge.com/minecraft/mc-mods/proper-finite-water with its default configuration if possible and remove the mod `Water Control Extreme`
Go into the Better With Mods config file and turn the feature `HCbuckets` on, then stress test it. **In survival**, scoop and place water several times, check that it _doesn't_ remove the source and that it _doesn't_ place a source block; if possible, spawn a bunch of entities and crank the render distance to 20 or more to lag the server.

**Comment by KaleThyself** [comment]
### Version: 
`ProperFiniteWater--mc1.12--1.01.jar`

### Finds (as of 12/21/22): 

- Attempting to right click any water from any bucket onto various herbs/grasses will create a source block of water which replaces the shrubbery instead of simply placing finite water. The most consistent testing I get is from placing water directly on placed rocks. 
- Holding down the right click button to bucket water allows you to re-bucket the water despite within a time frame despite not having an available source block to bucket from. The flimsy water bucket is able to consistently do this, but the quality water bucket fails after the second cycle. It requires a bit more careful timing, but it's still do-able.
